apiVersion: apps/v1
kind: Deployment
metadata:
  name: cator-contoso-traders-products
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cator-contoso-traders-products
  template:
    metadata:
      labels:
        app: cator-contoso-traders-products
    spec:
      nodeSelector:
        "kubernetes.io/os": linux
      containers:
        - name: cator-contoso-traders-products
          #Note: The '{ENVIRONMENT}' token will be substituted with the value of the ENVIRONMENT github secret by github workflow..
          image: contosotradersacr{ENVIRONMENT}.azurecr.io/contosotradersapiproducts:latest
          env:
            - name: KeyVaultEndpoint
              valueFrom:
                secretKeyRef:
                  name: contoso-traders-kv-endpoint
                  key: contoso-traders-kv-endpoint
            - name: ManagedIdentityClientId
              valueFrom:
                secretKeyRef:
                  name: contoso-traders-mi-clientid
                  key: contoso-traders-mi-clientid
          resources:
            requests:
              cpu: 250m
              memory: 256Mi
            limits:
              cpu: 500m
              memory: 512Mi
